// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHoAw_07im3PhS87dY2PbrmJzfGMf48w',
    appId: '1:240193263403:web:d345d75f896ec92893976e',
    messagingSenderId: '240193263403',
    projectId: 'haruhan',
    authDomain: 'haruhan.firebaseapp.com',
    storageBucket: 'haruhan.appspot.com',
    measurementId: 'G-6FD0KVWEH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWHXNQzL0KnTHeD3tH07tqDe6NjQQFNc',
    appId: '1:240193263403:android:69a06d164f04b76893976e',
    messagingSenderId: '240193263403',
    projectId: 'haruhan',
    storageBucket: 'haruhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTh_LYlYhXhu8_19kBfWmcTlC1RQi5G0g',
    appId: '1:240193263403:ios:58ef68c669f3ef9f93976e',
    messagingSenderId: '240193263403',
    projectId: 'haruhan',
    storageBucket: 'haruhan.appspot.com',
    iosBundleId: 'com.example.haruhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTh_LYlYhXhu8_19kBfWmcTlC1RQi5G0g',
    appId: '1:240193263403:ios:36bf62344e971ede93976e',
    messagingSenderId: '240193263403',
    projectId: 'haruhan',
    storageBucket: 'haruhan.appspot.com',
    iosBundleId: 'com.example.haruhan.RunnerTests',
  );
}
