import 'package:flutter/material.dart';

void main() {
  runApp(const DiscoverScreen());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class DiscoverScreen extends StatelessWidget {
  const DiscoverScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Discover1(),
        ]),
      ),
    );
  }
}

class Discover1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(44),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      // Positioned(
                      //   left: 289.67,
                      //   top: 17.33,
                      //   child: Container(
                      //     width: 66.66,
                      //     height: 11.34,
                      //     child: Stack(
                      //       children: [
                      //         Positioned(
                      //           left: 42.33,
                      //           top: 0,
                      //           child: Container(
                      //             width: 24.33,
                      //             height: 11.33,
                      //             //child: Stack(children:]),
                      //           ),
                      //         ),
                      //       ],
                      //     ),
                      //   ),
                      // ),
                      Positioned(
                        left: 24,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          padding: const EdgeInsets.only(top: 1),
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 54,
                                height: 20,
                                child: Text(
                                  '9:41',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 15,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w600,
                                    height: 0.09,
                                    letterSpacing: -0.50,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 44,
                child: Container(
                  width: 375,
                  height: 685,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 97,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            Container(
                              width: 343,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: double.infinity,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Text(
                                          'Discover',
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 34,
                                            fontFamily: 'SF Pro Text',
                                            fontWeight: FontWeight.w600,
                                            height: 1.0,
                                            letterSpacing: 0.37,
                                          ),
                                        ),
                                        //const SizedBox(width: 180),
                                      ],
                                    ),
                                  ),
                                  Text(
                                    '다빈님 취향에 맞는 책을 추천하고 검색해요 ',
                                    style: TextStyle(
                                      color: Color(0x993C3C43),
                                      fontSize: 13,
                                      fontFamily: 'SF Pro Text',
                                      fontWeight: FontWeight.w300,
                                      height: 1.0,
                                      letterSpacing: -0.24,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),
                      Container(
                        height: 206,
                        padding: const EdgeInsets.symmetric(horizontal: 16),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 41,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    '이런 책은 어떠세요? ',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'SF Pro Display',
                                      fontWeight: FontWeight.w600,
                                      height: 1.0,
                                      letterSpacing: 0.37,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 5),
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 109.20,
                                    height: 160,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: AssetImage('src/파친코.png'),
                                        fit: BoxFit.fill,
                                      ),
                                      boxShadow: [ boxShadow ],
                                    ),
                                  ),
                                  const SizedBox(width: 20),
                                  Container(
                                    width: 108.13,
                                    height: 160,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: AssetImage('src/세이노.png'),
                                        fit: BoxFit.fill,
                                      ),
                                      boxShadow: [boxShadow],
                                    ),
                                  ),
                                  const SizedBox(width: 20),
                                  Container(
                                    width: 109.20,
                                    height: 160,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: AssetImage('src/파친코2.png'),
                                        fit: BoxFit.fill,
                                      ),
                                      boxShadow: [ boxShadow],
                                    ),
                                  ),
                                  const SizedBox(width: 20),
                                  Container(
                                    width: 111.47,
                                    height: 160,
                                    decoration: BoxDecoration(
                                      image: DecorationImage(
                                        image: AssetImage('src/몰입.png'),
                                        fit: BoxFit.fill,
                                      ),
                                      boxShadow: [ boxShadow],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),
                      Container(
                        height: 334,
                        padding: const EdgeInsets.symmetric(horizontal: 16),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 50,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    '이번주 베스트셀러 Top 10',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'SF Pro Display',
                                      fontWeight: FontWeight.w600,
                                      height: 1.5,
                                      letterSpacing: 0.37,
                                    ),
                                  ),
                                  Text(
                                    '2023.10.16~2023.10.22 기준',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'SF Pro Text',
                                      fontWeight: FontWeight.w300,
                                      height: 1.0,
                                      letterSpacing: -0.24,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 15),
                            Container(
                              width: 343,
                              height: 269,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    width: 343,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Text(
                                          '1',
                                          style: BestSellerNum
                                        ),
                                        const SizedBox(width: 20),
                                        Container(
                                          width: 81,
                                          height: 120,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: AssetImage('src/트렌드코리아.png'),
                                              fit: BoxFit.fill,
                                            ),
                                            boxShadow: [ boxShadow],
                                          ),
                                        ),
                                        const SizedBox(width: 20),
                                        Container(
                                          width: 130, // 너비를 130으로 설정
                                          child: Text(
                                            '트렌드 코리아 2024',
                                            style: BestSellerTitle
                                          ),
                                        ),
                                        const SizedBox(width: 20),
                                        SizedBox(
                                          height: 33,
                                          child: Image.asset('src/chevron_fill.png')
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(height: 20),
                                  Container(
                                    width: double.infinity,
                                    height: 2,
                                    decoration: BoxDecoration(color: Color(0xFFDBDBDB)),
                                  ),
                                  const SizedBox(height: 20),
                                  Container(
                                    width: 343,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Text(
                                          '2',
                                          style: BestSellerNum
                                        ),
                                        const SizedBox(width: 20),
                                        Container(
                                          width: 82.80,
                                          height: 120,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: ExactAssetImage('src/퓨처셀프.png'),
                                              fit: BoxFit.fill,
                                            ),
                                            boxShadow: [ boxShadow],
                                          ),
                                        ),
                                        const SizedBox(width: 20),
                                        Container(
                                          width: 130, // 너비를 130으로 설정
                                          child: Text(
                                            '퓨처셀프',
                                            style: BestSellerTitle,
                                          ),
                                        ),
                                        const SizedBox(width: 20),
                                        SizedBox(
                                          height: 33,
                                          child: Image.asset('src/chevron.png')
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  TextStyle BestSellerNum = TextStyle(
    color: Colors.black,
    fontSize: 25,
    fontFamily: 'SF Pro Text',
    fontWeight: FontWeight.w400,
    height: 0.03,
    letterSpacing: -0.24,
  );

  TextStyle BestSellerTitle = TextStyle(
    color: Colors.black,
    fontSize: 15,
    fontFamily: 'SF Pro Text',
    fontWeight: FontWeight.w400,
    height: 0.09,
    letterSpacing: -0.24,
  );

  BoxShadow boxShadow = BoxShadow(
    color: Color(0x3F000000),
    blurRadius: 4,
    offset: Offset(0, 4),
    spreadRadius: 0,
  );
}