import 'package:flutter/material.dart';

// void main() {
//   runApp(const DiscoverDetailScreen());
// }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class DiscoverDetailScreen extends StatelessWidget {
  const DiscoverDetailScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(

      home: Scaffold(
        body: ListView(children: [
          Detail(),
        ]),
      ),
    );
  }
}

class Detail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 622,
                child: Container(
                  width: 375,
                  padding: const EdgeInsets.all(16),
                ),
              ),
              Positioned(
                left: 0,
                top: 44,
                child: Container(
                  width: 375,
                  height: 685,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 42,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              height: 32,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  SizedBox(
                                    width: 172,
                                    //height: 30,
                                    child :DefaultTextStyle(style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'SF Pro',
                                      fontWeight: FontWeight.w700,
                                      height: 1.0,
                                      ), child: Text('<  Discover')),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 10),
                      Container(
                        width: 136,
                        height: 201,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage('src/파친코2.png'),
                            fit: BoxFit.fill,
                          ),
                          boxShadow: [
                            BoxShadow(
                              color: Color(0x3F000000),
                              blurRadius: 4,
                              offset: Offset(0, 4),
                              spreadRadius: 0,
                            )
                          ],
                        ),
                      ),
                      //const SizedBox(height: 10),
                      Container(
                        width: double.infinity,
                        height: 63,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 343,
                              height: 63,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  SizedBox(
                                    width: 253,
                                    height: 40,
                                    child : DefaultTextStyle(style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontFamily: 'SF Pro',
                                      fontWeight: FontWeight.w600,
                                      height: 1.0,
                                    ), child: Text('파친코 2')),
                                  ),
                                  DefaultTextStyle(style: TextStyle(
                                    color: Color(0xFF979797),
                                    fontSize: 13,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: -0.23,
                                  ), child: Text('이민진 / 인플루엔셜')),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      //const SizedBox(height: 10),
                      Container(
                        width: double.infinity,
                        height: 144,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 317,
                              height: 144,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  SizedBox(
                                    width: 317,
                                    child: DefaultTextStyle(style: TextStyle(
                                      color: Color(0xFF3A3A3A),
                                      fontSize: 16,
                                      fontFamily: 'SF Pro',
                                      fontWeight: FontWeight.w400,
                                      //height: 0.09,
                                      letterSpacing: -1,
                                    ), child: Text('일제강점기 부산 끝에 자리한 작은섬 영도에 살던 훈이와 양진 부부가 낳은 딸 선자. 선자가 이삭을 따라 일본으로 이주해 간 후 낳은 노아와 모자수 그리고 그의 아들인 솔로몬에 이르기까지 4대에 걸친 일가족과 인물들에 대한 이야기')),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 10),
                      Container(
                        width: double.infinity,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 0.50,
                              strokeAlign: BorderSide.strokeAlignCenter,
                              color: Color(0xFFC6C6C8),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 15),
                      Container(
                        width: double.infinity,
                        height: 27,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 27,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  SizedBox(
                                    //width: 183,
                                    height: 20 ,
                                    child: DefaultTextStyle(
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF545454),
                                        fontSize: 20,
                                        fontFamily: 'SF Pro',
                                        fontWeight: FontWeight.w700,
                                        height: 1.0
                                    ), child: Text(' 찜하기 ')),
                                  ),
                                  const SizedBox(width: 5,),
                                  SizedBox(
                                    height: 20,
                                    child: Image.asset('src/chevron.png'),
                                  )
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}