import 'package:flutter/material.dart';
import 'package:http/http.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(children: [
          MyBookEx(),
        ]),
      ),
    );
  }
}

class MyBookEx extends StatefulWidget {
  @override
  _MyBookExState createState() => _MyBookExState();
}

class _MyBookExState extends State<MyBookEx> {
  int readState = 0;
  bool isLike = false; // 찜한책

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: double.infinity,
                height: 685,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: double.infinity,
                      height: 97,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.end,
                        children: [
                          Container(
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                DefaultTextStyle(style: myBook, child: Text('My Book')),
                                const SizedBox(height: 5,),
                                DefaultTextStyle(style: detail, child: Text('내가 읽은 책을 확인해요 ')),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    bookTitle('읽은 책  ', '8'),
                    const SizedBox(height: 24),
                    GestureDetector(
                      onTap: (){
                        setState((){
                          readState = (readState + 1)%4;
                        });
                      },
                      child: Container(
                        width: 343,
                        height: 188,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage(getImageForReadState(readState)),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    bookTitle('찜한 책  ', '5'),
                    const SizedBox(height: 24),
                    GestureDetector(
                      onTap: (){
                        setState((){
                          isLike = !isLike;
                        });
                      },
                      child: Container(
                        width: 343,
                        height: 188,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage(isLike? 'src/mybook2-1.png': 'src/mybook2.png'),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
  String getImageForReadState(int state) {
    // 각 상태에 따라 다른 이미지 경로를 반환
    switch (state) {
      case 0:
        return 'src/mybook1.png';
      case 1:
        return 'src/mybook1-1.png';
      case 2:
        return 'src/mybook1-2.png';
      default:
        return 'src/mybook1-3.png';
    }
  }
}


  Widget bookTitle(String title, String num){
    return SizedBox(
      width: 120,
      child: Text.rich(
        TextSpan(
          children: [
            TextSpan(
              text: title,
              style: bookStyle,
            ),
            TextSpan(
              text: num,
              style: bookNum,
            ),
          ],
        ),
      ),
    );
  }

  TextStyle myBook = TextStyle(
    color: Colors.black,
    fontSize: 34,
    fontFamily: 'SF Pro Display',
    fontWeight: FontWeight.w600,
    height: 1,
    letterSpacing: 0.37,
  );

  TextStyle detail = TextStyle(
    color: Color(0x993C3C43),
    fontSize: 13,
    fontFamily: 'SF Pro Text',
    fontWeight: FontWeight.w300,
    height: 1,
    letterSpacing: -0.24,
  );

  TextStyle bookStyle = TextStyle(
    color: Colors.black,
    fontSize: 22,
    fontFamily: 'SF Pro',
    fontWeight: FontWeight.w400,
    height: 1,
    letterSpacing: -1,
  );

  TextStyle bookNum = TextStyle(
    color: Color(0xFF81D8CF),
    fontSize: 23,
    fontFamily: 'SF Pro',
    fontWeight: FontWeight.w700,
    height: 1,
    letterSpacing: -1,
  );
