import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MyBookEx(),
        ]),
      ),
    );
  }
}

class MyBookEx extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          padding: const EdgeInsets.only(top: 44, bottom: 83),
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(44),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: double.infinity,
                height: 685,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: double.infinity,
                      height: 97,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.end,
                        children: [
                          Container(
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'My Book',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 34,
                                    fontFamily: 'SF Pro Display',
                                    fontWeight: FontWeight.w600,
                                    height: 1,
                                    letterSpacing: 0.37,
                                  ),
                                ),
                                const SizedBox(height: 5,),
                                Text(
                                  '내가 읽은 책을 확인해요 ',
                                  style: TextStyle(
                                    color: Color(0x993C3C43),
                                    fontSize: 13,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w300,
                                    height: 1,
                                    letterSpacing: -0.24,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),
                    SizedBox(
                      width: 120,
                      child: Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: '읽은 책',
                              style: bookStyle,
                            ),
                            TextSpan(
                              text: '  ',
                              style: TextStyle(
                                fontSize: 26,
                              ),
                            ),
                            TextSpan(
                              text: '8',
                              style: bookNum,
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    Container(
                      width: 343,
                      height: 188,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('src/mybook1.png'),
                          fit: BoxFit.fill,
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    SizedBox(
                      width: 120,
                      child: Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: '찜한 책',
                              style: bookStyle,
                            ),
                            TextSpan(
                              text: '  ',
                              style: TextStyle(
                                fontSize: 26,
                              ),
                            ),
                            TextSpan(
                              text: '5',
                              style: bookNum,
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    Container(
                      width: 343,
                      height: 188,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: AssetImage('src/mybook2.png'),
                          fit: BoxFit.fill,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  TextStyle bookStyle = TextStyle(
    color: Colors.black,
    fontSize: 22,
    fontFamily: 'SF Pro',
    fontWeight: FontWeight.w400,
    height: 1,
    letterSpacing: -1,
  );

  TextStyle bookNum = TextStyle(
    color: Color(0xFF81D8CF),
    fontSize: 23,
    fontFamily: 'SF Pro',
    fontWeight: FontWeight.w700,
    height: 1,
    letterSpacing: -1,
  );
}